# Parameters
Title="blgo" # Title of your site
Description="A static blog engine written in Go" # Description for your site
PreviewLength=30 # Length of the post preview in the index (number of words)

# Directories
Posts="posts" # Directory containing the posts
Templates="templates" # Directory containing the templates
Public="static" # Directory where the generated static site will be stored
